include:
  - project: 'widas/codequality'
    ref: master
    file: 'ci_templates/java.gitlab-ci.yml'

stages:
  - test
  - badges
  - deploy
  
before_script:
    - mkdir .m2
    - "echo -n $CIM_MAVEN_M2_SETTINGS_GENERAL > .m2/settings.xml"
    - "git config user.email 'devel@widas.de'"
    - "git config user.name 'devel'"